hkiesg/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
import news.urls

from search import views as search_views

urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("news/", include(news.urls)),
    path("search/", search_views.search, name="search"),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.NewsListView.as_view(), name='news_list'),
    path('<int:pk>/', views.NewsDetailView.as_view(), name='detail'),
    # path('set-language/', views.set_language, name='set_language'),
] 

home/models.py
from django.db import models

from wagtail.models import Page
from wagtail.admin.panels import FieldPanel
from wagtail.fields import RichTextField
from wagtail.fields import StreamField
from wagtail.blocks import RichTextBlock, CharBlock,RawHTMLBlock,URLBlock,StructBlock,ListBlock
from wagtail.images.blocks import ImageChooserBlock
from wagtail import blocks  
from wagtail.blocks import PageChooserBlock
from wagtail.snippets.models import register_snippet




class HomePage(Page):
    banner_title1 = models.CharField(max_length=255, default="默认标题")
    banner_title2 = models.CharField(max_length=255, default="默认标题")
    middle_title = models.CharField(max_length=255, default="默认中间标题") 
    group_4 = StreamField([
        ('raw_html', RawHTMLBlock()),
    ], blank=True)  # 使用 StreamField 包含 RawHTMLBlock
    content_panels = Page.content_panels + [
        FieldPanel("banner_title1"),
        FieldPanel("banner_title2"),
        FieldPanel("middle_title"),
        FieldPanel("group_4")
    ] 
    
    pass

class AboutPage(Page):
    pass

class ServicesPage(Page):
    pass

class ActivitiesPage(Page):
    pass

class MembersPage(Page):
    pass

@register_snippet
class Logo(models.Model):
    logo = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )
    alt_text = models.CharField(max_length=100, blank=True, help_text="Logo的替代文本")

    panels = [
        FieldPanel('logo'),
        FieldPanel('alt_text'),
    ]

    def __str__(self):
        return self.alt_text or "Logo"

    class Meta:
        verbose_name = "网站Logo"
        verbose_name_plural = "网站Logo"

menus/models.py
from django.db import models
from wagtail.admin.panels import FieldPanel
from wagtail.snippets.models import register_snippet
from wagtail.fields import StreamField
from wagtail.blocks import CharBlock, StructBlock, ListBlock, PageChooserBlock

class MenuItemBlock(StructBlock):
    title_zh = CharBlock(label="中文菜单名称")
    title_en = CharBlock(label="英文菜单名称")
    link_page_zh = PageChooserBlock(label="中文页面", required=False, can_choose_root=True)
    link_page_en = PageChooserBlock(label="英文页面", required=False, can_choose_root=True)
    sub_items = ListBlock(StructBlock([
        ('title_zh', CharBlock(label="中文子菜单名称")),
        ('title_en', CharBlock(label="英文子菜单名称")),
        ('link_page_zh', PageChooserBlock(label="中文页面", required=False)),
        ('link_page_en', PageChooserBlock(label="英文页面", required=False)),
    ]), label="子菜单项", required=False)

    class Meta:
        icon = 'link'

@register_snippet
class MainMenu(models.Model):
    menu_items = StreamField([
        ('menu_item', ListBlock(MenuItemBlock())),
    ], use_json_field=True)

    panels = [
        FieldPanel("menu_items"),
    ]

    def __str__(self):
        return "主导航菜单"

    class Meta:
        verbose_name = "主导航菜单"
        verbose_name_plural = "主导航菜单"

news/models.py
from django.db import models
from django.utils import timezone
from wagtail.admin.panels import FieldPanel, MultiFieldPanel
from wagtail.fields import RichTextField
from wagtail.models import TranslatableMixin
from wagtail.admin.panels import Panel
from wagtail.admin.panels import FieldPanel as WagtailFieldPanel

class NewsArticle(TranslatableMixin, models.Model):
    title = models.CharField("标题", max_length=200)
    subtitle = models.CharField("副标题", max_length=200, blank=True)
    content = RichTextField("内容")
    publish_date = models.DateTimeField("发布时间", default=timezone.now)
    is_published = models.BooleanField("是否发布", default=False)
    featured_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+',
        verbose_name="封面图片"
    )
    
    panels = [
        MultiFieldPanel([
            WagtailFieldPanel('title'),
            WagtailFieldPanel('subtitle'),
            WagtailFieldPanel('featured_image'),
        ], heading="基本信息"),
        WagtailFieldPanel('content'),
        MultiFieldPanel([
            WagtailFieldPanel('publish_date'),
            WagtailFieldPanel('is_published'),
        ], heading="发布设置")
    ]
    
    class Meta:
        verbose_name = "动态文章"
        verbose_name_plural = verbose_name
        ordering = ['-publish_date']
        constraints = [
            models.UniqueConstraint(
                fields=['translation_key', 'locale'],
                name='unique_translation_key_locale_news_newsarticle'
            )
        ]
    
    def __str__(self):
        return self.title

menus/views.py
from django.shortcuts import render

# Create your views here.

news/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import NewsArticle

# Create your views here.

class NewsListView(ListView):
    model = NewsArticle
    template_name = 'news/news_list.html'
    context_object_name = 'news_list'
    paginate_by = 10
    
    def get_queryset(self):
        return NewsArticle.objects.filter(
            is_published=True
        ).order_by('-publish_date')

class NewsDetailView(DetailView):
    model = NewsArticle
    template_name = 'news/news_detail.html'
    context_object_name = 'news'

search/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.template.response import TemplateResponse

from wagtail.models import Page

# To enable logging of search queries for use with the "Promoted search results" module
# <https://docs.wagtail.org/en/stable/reference/contrib/searchpromotions.html>
# uncomment the following line and the lines indicated in the search function
# (after adding wagtail.contrib.search_promotions to INSTALLED_APPS):

# from wagtail.contrib.search_promotions.models import Query


def search(request):
    search_query = request.GET.get("query", None)
    page = request.GET.get("page", 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)

        # To log this query for use with the "Promoted search results" module:

        # query = Query.get(search_query)
        # query.add_hit()

    else:
        search_results = Page.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return TemplateResponse(
        request,
        "search/search.html",
        {
            "search_query": search_query,
            "search_results": search_results,
        },
    )

hkiesg/templates/base.html
{% load static wagtailcore_tags wagtailuserbar %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>
            {% block title %}
            {% if page.seo_title %}{{ page.seo_title }}{% else %}{{ page.title }}{% endif %}
            {% endblock %}
            {% block title_suffix %}
            {% wagtail_site as current_site %}
            {% if current_site and current_site.site_name %}- {{ current_site.site_name }}{% endif %}
            {% endblock %}
        </title>
        {% if page.search_description %}
        <meta name="description" content="{{ page.search_description }}" />
        {% endif %}
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {# Force all links in the live preview panel to be opened in a new tab #}
        {% if request.in_preview_panel %}
        <base target="_blank">
        {% endif %}

        {# Global stylesheets #}
        <link rel="stylesheet" type="text/css" href="{% static 'css/hkiesg.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" /> 

        {% block extra_css %}
        {# Override this in templates to add extra stylesheets #}
        {% endblock %}
    </head>

    <body class="{% block body_class %}{% endblock %}">
        {% wagtailuserbar %}

        {% block content %}{% endblock %}

        {# Global javascript #}
        <script type="text/javascript" src="{% static 'js/hkiesg.js' %}"></script>

        {% block extra_js %}
        {# Override this in templates to add extra javascript #}
        {% endblock %}

        {% include 'home/footer.html' %}
    </body>
</html>

home/templates/home/about_page.html
{% load static wagtailcore_tags wagtailuserbar %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{page.title}}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
<link href="{% static 'css/swiper-bundle.min.css' %}" rel="stylesheet" type="text/css">
  </head>
  <body>
    <div class="flex-col page">
      <div class="flex-col self-stretch sc-section ">
  
        {% include 'home/header.html' %}

        <div class="innerbanner gybanner">
        <div class=" w1400 center pt-100">
     
          <!-- <div class="">
           <img src="{% static 'images/gy1.png' %}">  
          </div> -->

          <div class="self-stretch">
            <span class="font_20">
              ABOUT 
              <br />
            </span>
            <span class="font_20">
              US
              <br />
            </span>
            <span class="font_20 mt-31" style="font-size: 35px;margin-top: 10px;">
              关于我们
              <br />
            </span>
          </div>
          <div class="flex-col justify-start items-center self-start text-wrapper mt-31">
            <span class="font_4 text"><a href="#footer" style="color: white;">联系我们</a></span>
          </div>


        </div>
      </div>
      </div>
</div>
  
 
<div class="insection about_ingy1"  style="text-align: center; margin-top: 125px;">
  <span class="self-start text_356" >协会简介</span> 
  <div  style="margin-top: 25px;">
    <span class="font_9 text_14">
    香港可持续发展协会是专注于环境、社会和治理（ESG）领域的非盈利性组织，致力于推动香港地区可持续发展目标的实现，
  </span>
    <br>
    <span class="font_9 text_14">
    促进香港与内地以及亚太、中东地区的企业和投资者在ESG领域的发展与合作，为香港参与共建"一带一路”提供支撑与服务。
    </span> 
  </div>
</div>  



<div class="insection flex-row justify-between items-center self-stretch w1400 center ingy22">
  <div class="flex-col group_333">
    <div class="flex-col self-stretch">
      <span class="self-start text_356">协会宗旨</span>
      <span class="self-start text_3563">善治共赢</span>
      <div>
        <span class="font_141 text_14 text_20">
          负责任的、可持续的增长，即"善治"，共同分享成功，即"共赢”。即人们常说的"商业向善”。这不仅是一种道德责任，更是一种具备长期价值的商业策略。          
          <br />
          <br />    
        在《道德经》第八章中，老子提出"上善若水。水善利万物而不争。”这里的"善”，并不是指人伦意义上的善良或做好事，而是指一种至高无上的德行或智慧。结合ESG（环境、社会和治理）框架加以理解，从环境层面，"善"可以理解为对自然环境的尊重和保护；从社会层面，"善"意味着对社会福祉的贡献和对社会责任的担当；从治理层面，"善"体现为保持原则和道德的一致性。将"善”的理念融入ESG框架，意味着追求一种和谐、平衡和可持续的发展方式，尊重所有利益相关者的权益。
        <br />  <br />
        </span>

        <span class="font_141 text_14">
          如何做到善治共赢，就是要在促进长期价值创造的同时，减少对社会和环境的负面影响。
        </span>
      </div> 
    </div>
   
  </div>
  <img
    class="aboutimg4"
    src="{% static 'images/aboutimg4.png' %}"
  />
</div>


 
<div class="insection ingy3">
  
</div>
<div class="insection ingy4">
  
</div>
<div class="ingy5-wrap">
  <div class="insection ingy5">
  
</div>

<div style="text-align: center;"  class="ingy6-wrap">
  <div class="insection">   
  <span class="self-start text_356" >合作伙伴</span> 
  <div  style="margin-top: 25px;">
    <span class="font_9 text_14">
      香港可持续发展协会将汇聚各方力量，促进ESG意识的普及和实践水平的提升，推动香港地区可持续发展目标的实现，
  </span>
    <br>
    <span class="font_9 text_14">
      为构建一个更加繁荣、公正和可持续的社会贡献力量。
    </span> 
  </div>
  </div>
</div>  

 

<div class="w1400 center swiper-wrap-container">

<div class="swiper" id="gyswiper">
  <div class="swiper-wrapper">
      <div class="swiper-slide"><img src="{% static 'images/linlogo1.png' %}"></div>
      <div class="swiper-slide"><img src="{% static 'images/linlogo2.png' %}"></div>
      <div class="swiper-slide"><img src="{% static 'images/linlogo3.png' %}"></div>
      <div class="swiper-slide"><img src="{% static 'images/linlogo1.png' %}"></div>
      <div class="swiper-slide"><img src="{% static 'images/linlogo2.png' %}"></div>
      <div class="swiper-slide"><img src="{% static 'images/linlogo3.png' %}"></div>
      <div class="swiper-slide"><img src="{% static 'images/linlogo1.png' %}"></div>
      <div class="swiper-slide"><img src="{% static 'images/linlogo2.png' %}"></div>
      <div class="swiper-slide"><img src="{% static 'images/linlogo3.png' %}"></div>
  </div>
</div>
  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>
</div>
</div>

<div style="height: 144px;    background-color: #f6f6f6;"></div>
<div id="footer">
  {% include 'home/footer.html' %}
</div> 
  </body>
    <script src="{% static 'js/swiper-bundle.min.js' %}"></script>
  <script type="text/javascript">
    var mySwiper = new Swiper('.swiper', {
  autoplay: true,
    loop: true,
    slidesPerView :4,
  navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    },
})
  </script>
</html>

home/templates/home/activities_page.html
{% load i18n wagtailcore_tags %}
{% load static wagtailcore_tags wagtailuserbar %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{page.title}}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

  </head>
  <body> 

 

    <div class="flex-col page"></div>
      <div class="flex-col self-stretch sc-section ">
        
        {% include 'home/header.html' %}
        <div class="innerbanner hdbanner">
        <div class=" w1400 center pt-150">
          <div class="self-stretch">
            <span class="font_20">
              EVENTS 
              <br /> <br />
            </span> 
            <span class="font_20 mt-31" style="font-size: 35px;margin-top: 10px;">
              活动
              <br />
            </span>
          </div>
          <div class="flex-col justify-start items-center self-start text-wrapper mt-31">
            <span class="font_4 text"><a href="#footer" style="color: white;">联系我们</a></span>
          </div>
<!--      
          <div class="">
           <img src="{% static 'images/hd1.png' %}">
          </div> -->
        </div>
      </div>
      </div>
</div>











<div class="insection inhd1">
  
</div>
<div class="insection inhd2">
  
</div>


          {% include 'home/footer.html' %}
  </body>
</html>

home/templates/home/footer.html
{% load i18n wagtailcore_tags menu_tags %}
{% get_main_menu as menu_data %}
{% load static %}
<div class="footer-wrap ">
    <div class="flex-col section_8 w1400 center">
          <div class="flex-row justify-between group_34">
            <div class="flex-row">
              <a href="/">
              <img
                class="image_16"
                src="{% static 'images/blogo.png' %}"
              />
              </a>




              <div class="ml-70 flex-row self-start group_35"> 

                {% for block in menu_data.menu.menu_items %}
                {% for item in block.value %}   
                {% if forloop.first %}              
                      {% if menu_data.current_language == 'zh-hans' %} 
                        <span class="ml-24 font">
                          <a href="{% if item.link_page_zh %}{% pageurl item.link_page_zh %}{% else %}#{% endif %}" style="color: white;">
                              {{ item.title_zh }}
                          </a></span>
                      {% else %}
                        <span class="ml-24 font">
                        <a href="{% if item.link_page_en %}{% pageurl item.link_page_en %}{% else %}#{% endif %}" style="color: white;">
                            {{ item.title_en }}
                        </a></span>
                      {% endif %}
                    {% else %} 
                      {% if menu_data.current_language == 'zh-hans' %} 
                        <span class="ml-24 font">
                          <a href="{% if item.link_page_zh %}{% pageurl item.link_page_zh %}{% else %}#{% endif %}" style="color: white;">
                              {{ item.title_zh }}
                          </a></span>
                      {% else %}<span class="ml-24 font">
                        <a href="{% if item.link_page_en %}{% pageurl item.link_page_en %}{% else %}#{% endif %}" style="color: white;">
                            {{ item.title_en }}
                        </a></span>
                      {% endif %}
                    {% endif %}
                {% endfor %}
                {% endfor %}
 



              </div>




            </div>
            <div class="flex-col self-start group_36">
              <div class="flex-row items-center self-stretch group_2"> 


                <span class="font"><a href="https://www.hkiesg.com/" style="color: white;">中 文</a></span>
                <span class="font_2 ml-23"><a href="https://en.hkiesg.com/" style="color: white;">English</a></span>
              </div>
              <div class="self-start section_2"></div>
            </div>
          </div>
          <div class="mt-96 flex-col">
            <div class="flex-row self-stretch group_37">
              <div class="shrink-0 self-center group_38">
                <span class="font_16">
                  地址
                  <br />
                </span>
                <span class="font_16">香港皇后大道中183號中遠大廈11樓1103A室</span>
              </div>
              <div class="flex-row shrink-0 self-center group_39">
                <div class="shrink-0 group_38">
                  <span class="font_16">
                    电子邮件
                    <br />
                  </span>
                  <span class="font_16">info@hkiesg.com</span>
                </div>
                <div class="ml-24 shrink-0 group_38">
                  <span class="font_16">
                    电话
                    <br />
                  </span>
                  <span class="font_16">（+852）6877 0745</span>
                </div>
              </div>
              <div class="flex-row shrink-0 self-start group_40">
                <!-- <img
                  class="image_17"
                  src="{% static 'images/wx.png' %}"
                /> -->
                <div class="ml-24 flex-col justify-start items-center text-wrapper_3">
                  <span class="font_4 text_35">联系我们</span>
                </div>
              </div>
            </div>
            <span class="self-start text_36 mt-19">© 2024hkiesg . All rights reserved</span>
          </div>
        </div>
        </div>

home/templates/home/header.html
{% load i18n static wagtailcore_tags wagtailimages_tags menu_tags wagtailuserbar %}
{% get_main_menu as menu_data %}
<div class="flex-row justify-between self-stretch w1400 center navwrap">
  <div class="flex-row items-center">
 

    {% if site_logo and site_logo.logo %}
    {% image site_logo.logo original as logo_image %}
    <a href="/" class="logo">
        <img src="{{ logo_image.url }}" alt="{{ site_logo.alt_text }}" class="image">
    </a>
  {% endif %}


    <div class="ml-84 flex-row innernav">
    {% for block in menu_data.menu.menu_items %}
    {% for item in block.value %}   
    {% if forloop.first %}              
        {% if menu_data.current_language == 'zh-hans' %} <span class="font ml-40">
          <span class="font">
            <a href="{% if item.link_page_zh %}{% pageurl item.link_page_zh %}{% else %}#{% endif %}" style="color: black;">
                {{ item.title_zh }}
            </a></span>
        {% else %}<span class="font">
          <a href="{% if item.link_page_en %}{% pageurl item.link_page_en %}{% else %}#{% endif %}" style="color: black;">
              {{ item.title_en }}
          </a></span>
        {% endif %}
        {% else %} 
        {% if menu_data.current_language == 'zh-hans' %} <span class="font ml-40">
          <span class="font navitem">
            <a href="{% if item.link_page_zh %}{% pageurl item.link_page_zh %}{% else %}#{% endif %}" style="color: black;">
                {{ item.title_zh }}
            </a></span>
        {% else %}<span class="font navitem">
          <a href="{% if item.link_page_en %}{% pageurl item.link_page_en %}{% else %}#{% endif %}" style="color: black;">
              {{ item.title_en }}
          </a></span>
        {% endif %}
        {% endif %}
    {% endfor %}
    {% endfor %}
  </div>






<!-- 
    <div class="ml-84 flex-row innernav">
      <span class="font"><a href="{% pageurl page %}" style="color: black;">首 页</a></span>
      <span class="font navitem"><a href="/about" style="color: black;">关于我们</a></span>
      <span class="font navitem"><a href="/member" style="color: black;">会 员</a></span>
      <span class="font navitem"><a href="/service" style="color: black;">服 务</a></span>
      <span class="font navitem"><a href="/activities" style="color: black;">活 动</a></span>
      <span class="font navitem"><a href="/" style="color: black;">加入我们</a></span>
    </div>

-->
 







  </div>
  <div class="flex-col self-start group innernav">
    <div class="flex-row items-center self-stretch group_2 ">
      <span class="font"><a href="https://www.hkiesg.com/" style="color: black;">中 文</a></span>
          <span class="font_2 ml-23"><a href="https://en.hkiesg.com/" style="color: black;">English</a></span>
    </div>
    <div class="self-start section_2"></div>
  </div>
</div>

home/templates/home/members_page.html
{% load i18n wagtailcore_tags %}
{% load static wagtailcore_tags wagtailuserbar %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{page.title}}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

  </head>
  <body>
    <div class="flex-col page">
      <div class="flex-col self-stretch sc-section ">
       

        {% include 'home/header.html' %}
        <div class="innerbanner hybanner">
        <div class=" w1400 center pt-150">     

          
          <div class="self-stretch">
            <span class="font_20">
              MEMBERSHIPS 
              <br /> <br />
            </span> 
            <span class="font_20 mt-31" style="font-size: 35px;margin-top: 10px;">
              会员
              <br />
            </span>
          </div>
          <div class="flex-col justify-start items-center self-start text-wrapper mt-31">
            <span class="font_4 text"><a href="#footer" style="color: white;">联系我们</a></span>
          </div>


          <!-- <div class="">





           <img src="{% static 'images/hy1.png' %}">  
          </div> -->
        </div>
      </div>
      </div>
</div>
<div class="insection about_ingy1"  style="text-align: center; margin-top: 125px;">
  <span class="self-start text_356" >会 员</span> 
  <div  style="margin-top: 25px;">
    <span class="font_9 text_14">
      HKIESG作为非盈利机构，由业界有志之士和专业力量所组成，旨在推动香港成为国际可持续发展的典范，
    </span>
    <br>
    <span class="font_9 text_14">
      充分发挥香港在“双循环”可持续发展新格局中的重要枢纽作用。
    </span> 
    <br>
    <span class="font_9 text_14">
      为了实现这一目标，HKIESG强调要加强香港与内地、中东与亚太地区在ESG领域的合作。
    </span> 
    <br>
    <br>
    <span class="font_9 text_14">
      HKIESG 会员计划面向香港、大陆、中东以及亚太地区的所有参与者开放。加入会员须经过HKIESG 执行委员会批准。
    </span> 

  </div>
</div>   
<div class="insection flex-row justify-between items-center self-stretch w1400 center ingy22">
  <div class="flex-col group_333">
    <div class="flex-col self-stretch">
      <span class="self-start text_356">会员福利</span> 
      <div class="esg-report">
        <span style="height: 10px;">
        <h2 style="float: left;">独家研究报告</h2>
        <p> ：&nbsp;理解香港ESG领域的最新趋势和发展。</p>
      </span>
      <span style="height: 10px;">

        <h2 style="float: left;">培训教育机会</h2>
        <p> ：&nbsp;参与各类研讨会和培训课程，提升专业知识和技能。</p>
      </span>
        <span>
        <h2 style="float: left;">行业网络拓展</h2>
        <p> ：&nbsp;与行业内的专业人士建立联系，促进资源共享和合作机会。</p>
        </span>
        <h2  style="float: left;">品牌推广支持</h2>
        <p> ：&nbsp;通过活动提升自身的品牌知名度，展示会员在ESG领域的成就和承诺。</p>
        
        <h2 style="float: left;">专业ESG咨询</h2>
        <p> ：&nbsp;帮助会员在ESG方面做出更明智的决策，提升实践水平。</p>
        
        <h2 style="float: left;">政策倡导参与</h2>
        <p> ：&nbsp;参与工作组，参与及带领各业界的可持续发展倡议、政策及措施。</p>
      </div>
      <span class="self-start text_356">成为会员</span> 
      <div class="esg-report-div">请将您的入会申请发送到INFO@HKIESG.COM。我们将尽快联系您。</div>
   
    </div>
 
  </div>
  
  <img class="aboutimg4" src="{% static 'images/img555.png' %}" alt="会员福利" />
</div>
 

<!-- <div class="insection inhy1">
  
</div> -->
<!-- <div class="insection inhy2">
  
</div> -->

{% include 'home/footer.html' %}
  </body>
</html>

news/templates/news/news_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>News List</title>
</head>
<body>
    <h1>新闻列表</h1>
    {% if news_list %}
    <p>找到 {{ news_list.count }} 条新闻</p>
    {% for article in news_list %}
        <h2>{{ article.title }}</h2>
        <p>{{ article.subtitle }}</p>
        <time>{{ article.publish_date|date:"Y-m-d" }}</time>
        <a href="{% url 'news:detail' article.pk %}">阅读更多</a>
    {% endfor %}
{% else %}
    <p>暂无新闻</p>
{% endif %}
</body>
</html>